---
title: "ir_sample_workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ir_sample_workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ir)
```


```{r, eval = FALSE}
d <- ir::ir_import_spc(filenames = list.files("./../../analysis/data/raw_data/grams/", full.names = TRUE))

# d$spectra[[1]]$x[1] <- 2000

x <- ir::ir_bc(x = d, method = "rubberband", return_bl = TRUE)

x <- ir::ir_bin(x, width = 5)

# x <- ir::ir_clip(x, range = c(1300, 2700))

x <- ir::ir_normalise(x, method = 1400)

x <- ir::ir_smooth(x, method = "sg", n = 9)

x <- ir::ir_interpolate(x, start = NULL, dw = 1)

x <- ir::ir_interpolate_region(x, region = c(1200, 1400))

# x$spectra$`1`$y[(ir::ir_get_wavenumberindex(ir_flatten(x), wavenumber = c(1200))-10):(ir::ir_get_wavenumberindex(ir_flatten(x), wavenumber = c(1400))+10)] <- NA

x$group1 <- c(rep(1, 4), rep(2, 5))
x$group2 <- c(rep(1:4, each = 2), 5)

x_avg <- ir::ir_average(x, group1, group2)

d <- ir::ir_import_spc(filenames = list.files("./analysis/data/raw_data/grams/", full.names = TRUE))

x <- ir::ir_sample_data

x <- irpeat::irp_content_klh_hodgkins(x = x, export = NULL, verbose = TRUE, make_plots = FALSE)

x <- irpeat::irp_hi(x)

```
